apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: rollout-reporter-sa
  namespace: my-cf

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: rollout-reporter-sa
  namespace: my-cf
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rollout-reporter-sa
  namespace: my-cf
roleRef:
  apiGroup: ""
  kind: Role
  name: rollout-reporter-sa
subjects:
- kind: ServiceAccount
  name: rollout-reporter-sa
  namespace: my-cf
